### ISSUE TITLE
Doesn't detect keywords in string interpolation

### ISSUE THREAD

**Issue by dylanpyle** [benchling/coffeelint-forbidden-keywords#3] opened 2015-02-25 23:18 UTC
Haven't looked into the coffeelint API to know if this is a limitation of the tool itself, but this rule doesn't appear to prevent misbehavior inside string interpolation.

For example, with the following rules:

```
"forbidden_keywords": {
  "module": "coffeelint-forbidden-keywords",
  "level": "error",
  "forbidden": {
    "==": "is",
    "!=": "isnt",
    "&&": "and",
    "||": "or",
    "!": "not",
    "this": "@"
  }
}
```

Something like the following is caught as expected:

```
fn = ->
  this.bar == 2

     ✗ #2: The "this" keyword is forbidden. Use "@" instead.
     ✗ #2: The "==" keyword is forbidden. Use "is" instead.
```

But this isn't:

```
fn = ->
  "hmm... #{this.bar == 2}"
```

**Comment by saifelse** [comment] 2015-02-26 03:49
This is caused by a bug in `coffeescript` that was resolved in v1.8.0: https://github.com/jashkenas/coffeescript/pull/3533

If you upgrade `coffeelint` to 1.9.2, it will use the newer `coffeescript` binary, which does not have this bug.

**Closed** 2017-08-23 19:58 UTC
